#!/bin/sh

# .husky/commit-msg
# Skip commit message validation for semantic-release commits
if grep -q '\[skip ci\]' "$1"; then
  echo "Skipping commitlint for semantic-release commit"
  exit 0
else
  # Get the current branch
  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

  # Set the branch you want to skip
  MAIN_BRANCH="main"

  # Check if the current branch is different from main
  if [ "$CURRENT_BRANCH" != "$MAIN_BRANCH" ]; then
    echo "Running pre-commit hook on branch: $CURRENT_BRANCH"

    # Add the commands or tools you want to run here
    npm run test:type
    npm run test:unit
    npm run lint:fix
  else
    echo "Skipping pre-commit hook on the main branch"
  fi
fi

npx --no-install commitlint --edit "$1"



